smartbozor/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from django_otp.admin import OTPAdminSite

from apps.parking.views import ParkingActionView
from apps.payment.views import PaymentQrStallView, PaymentClick, PaymentPayme, PaymentQrShopView, PaymentQrRentView, \
    PaymentQrParkingView, PaymentQrPoint, PaymentClickPointProduct
from smartbozor.storages import stall_storage

urlpatterns = [
    path('control/', admin.site.urls),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("api/", include("apps.api.urls")),

    path("s/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrStallView.as_view(), name="stall-qr"),
    path("m/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrShopView.as_view(), name="shop-qr"),
    path("r/<int:bazaar_id>-<int:thing_id>-<int:number>/", PaymentQrRentView.as_view(), name="thing-qr"),
    path("p/<int:pk>/", PaymentQrParkingView.as_view(), name="parking-qr"),
    path("x/<int:pk>/", PaymentQrPoint.as_view(), name="point-qr"),

    path("parking/<str:action>/<str:token>/", ParkingActionView.as_view(), name="action"),

    path("payment/click/<str:name>/", PaymentClick.as_view(), name="payment-click"),
    path("payment/click/x/<str:slug>/", PaymentClickPointProduct.as_view(), name="payment-x-click"),
    path("payment/payme/<str:name>/", PaymentPayme.as_view(), name="payment-payme"),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(stall_storage.base_url, document_root=stall_storage.location)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path("", include( "apps.main.urls")),

    path("ai/", include("apps.ai.urls")),
    path("payment/", include("apps.payment.urls")),
    path("dashboard/", include( "apps.dashboard.urls")),
    path("account/", include( "apps.account.urls")),
    path("stall/", include( "apps.stall.urls")),
    path("shop/", include( "apps.shop.urls")),
    path("report/", include( "apps.report.urls")),
    path("parking/", include( "apps.parking.urls")),
    path("rent/", include( "apps.rent.urls")),
    path("camera/", include( "apps.camera.urls")),
)


admin.site.index_title = _('Smart bozor')
admin.site.site_header = _('Smart bozor')
admin.site.site_title = _('Smart bozor management')

if not settings.DEBUG:
    admin.site.__class__ = OTPAdminSite

apps/ai/models.py
import uuid
from datetime import timedelta, datetime

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.camera.models import Camera
from apps.main.models import Bazaar
from smartbozor.storages import stall_storage


class StallDataSet(models.Model):
    STATUS_NEW = 0
    STATUS_MARKED = 1
    STATUS_MARKED_MODERATED = 2
    STATUS_GENERATED = 3
    STATUS_WRONG = -1

    bazaar = models.ForeignKey(Bazaar, on_delete=models.RESTRICT, verbose_name=_("Bozor"))
    camera = models.ForeignKey(Camera, on_delete=models.RESTRICT, verbose_name=_("Kamera"))
    image = models.ImageField(verbose_name="Snapshot", storage=stall_storage)
    data = models.JSONField(verbose_name="AI data")
    status = models.SmallIntegerField(default=STATUS_NEW, db_index=True)
    snapshot_at = models.DateTimeField(null=True, default=None, blank=True, verbose_name="Snapshot date")

    @classmethod
    def get_snapshot_after(cls):
        today = timezone.localtime().date()
        snapshot_after_data = today - timedelta(days=360)
        return timezone.make_aware(
            datetime(snapshot_after_data.year, snapshot_after_data.month, snapshot_after_data.day)
        )

    class Meta:
        managed = False


class StallOccupation(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.RESTRICT, verbose_name=_("Kamera"), db_index=False)
    roi_id = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name=_("Roi ID"))
    state = models.SmallIntegerField(verbose_name=_("State"), editable=False)
    check_at = models.DateTimeField(verbose_name=_("Check at"), editable=False)

    class Meta:
        managed = False

templates/include/ajax-modal.j2
<div class="modal fade modal-lg" id="id-ajax-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <h5 class="modal-header">
                <span></span>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </h5>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

<script src="{{ static("js/ajax-modal.min.js") }}?{{ STATIC_VERSION }}"></script>

templates/include/months-dropdown.j2
{% set months_dropdown %}
<button type="button" data-bs-toggle="dropdown" class="btn btn-success py-1 dropdown-toggle">
    {{ current_month.name }}
</button>
<div class="dropdown-menu dropdown-menu-end">
    {% for mm in months %}
        <a href="?n={{ mm.n }}" class="dropdown-item {% if mm.n == n %}active text-white{% endif %}">
            {{ mm.name }}
        </a>
    {% endfor %}
</div>
{% endset %}

{% if calendar %}
    <div class="btn-group ms-auto">
        <div class="btn-group">
            {{ months_dropdown }}
        </div>

        <div class="btn-group">
            <button type="button" data-bs-toggle="dropdown" class="btn btn-success py-1 rounded-end">
                <i class="bi bi-calendar3"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-end border-0 shadow-lg p-3">
                {{ calendar|safe }}
            </div>
        </div>
    </div>
{% else %}
    <div class="dropdown ms-auto">
        {{ months_dropdown }}
    </div>
{% endif %}

templates/include/navbar.j2
<div class="bg-white shadow py-3 px-4 mb-4 rounded d-flex align-items-center">
    <strong>{{ PAGE_TITLE|default(TITLE) }}</strong>
    <div class="dropdown ms-auto">
        <span class="me-2">{{ request.user.last_name }} {{ request.user.first_name }}</span>
        <button type="button" class="btn btn-primary py-1 border-0 px-2 rounded-circle" data-bs-toggle="dropdown">
            <i class="bi bi-person-circle"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right border-0 shadow rounded">
            <div class="dropdown-item">
                <form method="post" action="{{ url("account:logout") }}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link p-0 text-decoration-none w-100 text-start">{{ _("Chiqish") }}</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/include/sidebar.j2
<div class="sidebar vh-100 overflow-y-auto shadow p-3 bg-white position-fixed top-0 start-0">
    <a href="{{ url("main:index") }}"
       class="d-flex align-items-center justify-content-center text-primary logo text-decoration-none fs-5 mb-4">
        <i class="bi bi-bar-chart-fill me-2"></i>
        smart bozor
    </a>

    <div class="px-3 py-2 rounded {{ is_active(request, "dashboard:index") }}">
        <a href="{{ url("dashboard:index") }}" class="text-decoration-none d-flex align-items-center">
            <i class="bi bi-speedometer2 me-2"></i>
            {{ _("Umumiy hisobot") }}
        </a>
    </div>

    {% if perms.report.can_view_total_revenue %}
        <div class="px-3 py-2 rounded {{ is_active(request, "report:total-revenue") }}">
            <a href="{{ url("report:total-revenue") }}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-graph-up-arrow me-2"></i>
                {{ _("Jami daromad") }}
            </a>
        </div>
    {% endif %}

    {% if perms.report.can_view_total_scan %}
        <div class="px-3 py-2 rounded {{ is_active(request, "report:total-scan") }}">
            <a href="{{ url("report:total-scan") }}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-qr-code-scan me-2"></i>
                {{ _("Jami skan") }}
            </a>
        </div>
    {% endif %}

    {% if perms.payment.view_click %}
        <div class="px-3 py-2 rounded {{ is_active(request, "report:total-click") }}">
            <a href="{{ url("report:total-click") }}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-wallet2 me-2"></i>
                {{ _("Click hisobot") }}
            </a>
        </div>
    {% endif %}

    {% if perms.stall.view_stall and ALLOWED_BAZAAR %}
        <div class="px-3 py-2 rounded {{ is_active(request, "stall:list-bazaar,stall:list") }}">
            <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("stall:list", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("stall:list-bazaar") }}{% endif %}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-dice-4 me-2"></i> {{ _("Rastalar ro'yxati") }}
            </a>
        </div>
    {% endif %}

    {% if perms.shop.view_shop and ALLOWED_BAZAAR %}
        <div class="px-3 py-2 rounded {{ is_active(request, "shop:list-bazaar,shop:list") }}">
            <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("shop:list", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("shop:list-bazaar") }}{% endif %}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-shop me-2"></i> {{ _("Do'konlar ro'yxati") }}
            </a>
        </div>
    {% endif %}

    {% if perms.rent.view_thing and ALLOWED_BAZAAR %}
        <div>
            <div class="px-3 py-2 rounded d-flex  {{ is_active(request, "rent:list,rent:list-bazaar", "text-primary") }}">
                <i class="bi bi-cart3 me-2"></i>
                {{ _("Ijara buyumlar") }}
                <i class="bi bi-chevron-down ms-auto"></i>
            </div>
            {% for thing in THINGS %}
                <div class="px-3 ps-4 py-2 rounded {{ is_active(request, "rent:list-bazaar,rent:list", "active", thing.id == pk) }}">
                    <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("rent:list", ALLOWED_BAZAAR[0].id, thing.id) }}{% else %}{{ url("rent:list-bazaar", thing.id) }}{% endif %}" class="text-decoration-none d-flex align-items-center">
                        <i class="bi bi-arrow-right me-2"></i> {{ thing }}
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if perms.parking.view_parking and ALLOWED_BAZAAR %}
        <div class="px-3 py-2 rounded {{ is_active(request, "parking:list-bazaar,parking:list") }}">
            <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("parking:list", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("parking:list-bazaar") }}{% endif %}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-car-front me-2"></i> {{ _("Avtoturargohlar") }}
            </a>
        </div>
    {% endif %}

    {% if perms.camera.view_camera and ALLOWED_BAZAAR %}
        <div class="px-3 py-2 rounded {{ is_active(request, "camera:list-bazaar,camera:list,camera:preview,camera:roi") }}">
            <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("camera:list", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("camera:list-bazaar") }}{% endif %}"
               class="text-decoration-none d-flex align-items-center">
                <i class="bi bi-camera-video me-2"></i> {{ _("Kameralar") }}
            </a>
        </div>
    {% endif %}

    {% if (perms.ai.add_stalldataset or perms.ai.change_stalldataset) and ALLOWED_BAZAAR %}
        <div>
            <div class="px-3 py-2 rounded d-flex  {{ is_active(request, "rent:list,rent:list-bazaar", "text-primary") }}">
                <i class="bi bi-cpu me-2"></i>
                {{ _("AI") }}
                <i class="bi bi-chevron-down ms-auto"></i>
            </div>
        </div>
        {% if perms.ai.add_stalldataset %}
            <div class="px-3 ps-4 py-2 rounded {{ is_active(request, "ai:stall-mark-bazaar,ai:stall-mark") }}">
                <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("ai:stall-mark", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("ai:stall-mark-bazaar") }}{% endif %}"
                   class="text-decoration-none d-flex align-items-center">
                    <i class="bi bi-arrow-right me-2"></i>  {{ _("Rastlarni belgilash") }}
                </a>
            </div>
        {% endif %}

        {% if perms.ai.change_stalldataset %}
            <div class="px-3 ps-4 py-2 rounded {{ is_active(request, "ai:stall-mark-moderate-bazaar,ai:stall-mark-moderate") }}">
                <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("ai:stall-mark-moderate", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("ai:stall-mark-moderate-bazaar") }}{% endif %}"
                   class="text-decoration-none d-flex align-items-center">
                    <i class="bi bi-arrow-right me-2"></i> {{ _("Rast bandligini tekshirish") }}
                </a>
            </div>
            <div class="px-3 ps-4 py-2 rounded {{ is_active(request, "ai:stall-mark-update-bazaar,ai:stall-mark-update") }}">
                <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("ai:stall-mark-update", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("ai:stall-mark-update-bazaar") }}{% endif %}"
                   class="text-decoration-none d-flex align-items-center">
                    <i class="bi bi-arrow-right me-2"></i> {{ _("Rast bandligini tahrirlash") }}
                </a>
            </div>
            <div class="px-3 ps-4 py-2 rounded {{ is_active(request, "ai:stall-test-bazaar,ai:stall-test") }}">
                <a href="{% if ALLOWED_BAZAAR|length==1 %}{{ url("ai:stall-test", ALLOWED_BAZAAR[0].id) }}{% else %}{{ url("ai:stall-test-bazaar") }}{% endif %}"
                   class="text-decoration-none d-flex align-items-center">
                    <i class="bi bi-arrow-right me-2"></i> {{ _("AI testlash") }}
                </a>
            </div>
        {% endif %}
    {% endif %}
</div>