apps/report/urls.py
from django.urls import path

from apps.report.views import ReportTotalRevenueView, ReportTotalScanView, ReportTotalClick

app_name = 'report'
urlpatterns = [
    path("total-revenue/", ReportTotalRevenueView.as_view(), name="total-revenue"),
    path("total-scan/", ReportTotalScanView.as_view(), name="total-scan"),
    path("total-click/", ReportTotalClick.as_view(), name="total-click"),
]

apps/stall/urls.py
from django.urls import path

from apps.stall.views import StallListView, StallQrCode, StallBazaarChoiceView, StallImportView

app_name = "stall"
urlpatterns = [
    path("list/", StallBazaarChoiceView.as_view(), name="list-bazaar"),
    path("list/<int:pk>/", StallListView.as_view(), name="list"),
    path("import/<int:pk>/", StallImportView.as_view(), name="import"),
    path("qr-code/<int:pk>/", StallQrCode.as_view(), name="qr-code")
]

smartbozor/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from django_otp.admin import OTPAdminSite

from apps.parking.views import ParkingActionView
from apps.payment.views import PaymentQrStallView, PaymentClick, PaymentPayme, PaymentQrShopView, PaymentQrRentView, \
    PaymentQrParkingView, PaymentQrPoint, PaymentClickPointProduct
from smartbozor.storages import stall_storage

urlpatterns = [
    path('control/', admin.site.urls),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("api/", include("apps.api.urls")),

    path("s/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrStallView.as_view(), name="stall-qr"),
    path("m/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrShopView.as_view(), name="shop-qr"),
    path("r/<int:bazaar_id>-<int:thing_id>-<int:number>/", PaymentQrRentView.as_view(), name="thing-qr"),
    path("p/<int:pk>/", PaymentQrParkingView.as_view(), name="parking-qr"),
    path("x/<int:pk>/", PaymentQrPoint.as_view(), name="point-qr"),

    path("parking/<str:action>/<str:token>/", ParkingActionView.as_view(), name="action"),

    path("payment/click/<str:name>/", PaymentClick.as_view(), name="payment-click"),
    path("payment/click/x/<str:slug>/", PaymentClickPointProduct.as_view(), name="payment-x-click"),
    path("payment/payme/<str:name>/", PaymentPayme.as_view(), name="payment-payme"),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(stall_storage.base_url, document_root=stall_storage.location)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path("", include( "apps.main.urls")),

    path("ai/", include("apps.ai.urls")),
    path("payment/", include("apps.payment.urls")),
    path("dashboard/", include( "apps.dashboard.urls")),
    path("account/", include( "apps.account.urls")),
    path("stall/", include( "apps.stall.urls")),
    path("shop/", include( "apps.shop.urls")),
    path("report/", include( "apps.report.urls")),
    path("parking/", include( "apps.parking.urls")),
    path("rent/", include( "apps.rent.urls")),
    path("camera/", include( "apps.camera.urls")),
)


admin.site.index_title = _('Smart bozor')
admin.site.site_header = _('Smart bozor')
admin.site.site_title = _('Smart bozor management')

if not settings.DEBUG:
    admin.site.__class__ = OTPAdminSite

apps/stall/models.py
import os

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from django.db.models import Count, Q
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.main.models import Section
from smartbozor.qrcode import generate_qr_code


class StallManager(models.Manager):
    def get_queryset(self):
        today = timezone.localtime().date()
        return super().get_queryset().annotate(
            status_count=Count("stallstatus__id", distinct=True, filter=Q(stallstatus__date=today) & (
                    Q(stallstatus__payment_progress__gt=0) | Q(stallstatus__is_paid=True)
            ))
        )


class Stall(models.Model):
    NUMBER_PATTERN = r"^[a-z0-9]+$"

    # objects = StallManager()

    section = models.ForeignKey(Section, on_delete=models.RESTRICT, verbose_name=_("Bo'lim nomi"))
    number = models.CharField(max_length=20, verbose_name=_("Rasta raqami"), validators=[
        RegexValidator(regex=NUMBER_PATTERN)
    ])
    price = models.IntegerField(verbose_name=_("Rasta narxi"), validators=[MinValueValidator(100)])

    @property
    def qr_image_file(self):
        cache_path = settings.MEDIA_ROOT / "qr-codes" / "stall" / str(self.id // 1000)
        os.makedirs(cache_path, exist_ok=True)

        cache_file = cache_path / f"{self.qr_data}.png"
        if os.path.exists(cache_file):
            return cache_file

        img = generate_qr_code("rasta-click.png", f"{settings.QR_CODE_LINK_HOST}/s/{self.qr_data}/", "RASTA",
                               self.number)
        img.save(cache_file, format="PNG", optimize=True, compress_level=9, dpi=(300, 300))
        img.close()

        return cache_file

    @property
    def qr_data(self):
        return "{0}-{1}-{2}-{3}".format(
            self.section.area.bazaar_id,
            self.section.area.id,
            self.section.id,
            self.number
        )

    class Meta:
        unique_together = ('section', 'number')
        verbose_name = _("Rasta")
        verbose_name_plural = _("Rastalar")


class StallStatus(models.Model):
    PAYMENT_PROGRESS_CLICK = 1
    PAYMENT_PROGRESS_PAYME = 2
    PAYMENT_PROGRESS_CASH = 3

    PAYMENT_PROGRESS_TITLE = {
        PAYMENT_PROGRESS_CLICK: "Click",
        PAYMENT_PROGRESS_PAYME: "Payme",
        PAYMENT_PROGRESS_CASH: _("Naqd"),
    }

    stall = models.ForeignKey(Stall, on_delete=models.RESTRICT, verbose_name=_("Rasta"))
    date = models.DateField(verbose_name=_("Kun"))
    is_occupied = models.BooleanField(default=False, verbose_name=_("Band bo'lgan"))
    is_paid = models.BooleanField(default=False, verbose_name=_("To'lov qilingan"))
    payment_method = models.IntegerField(default=0, verbose_name=_("To'lov turi"))
    payment_progress = models.SmallIntegerField(default=0, verbose_name=_("To'lov jarayoni"))
    price = models.IntegerField(verbose_name=_("Narxi"))
    occupied_at = models.DateTimeField(null=True, default=None, blank=True, verbose_name=_("Band qilingan sana"))
    paid_at = models.DateTimeField(null=True, default=None, blank=True, verbose_name=_("To'lov qilingan sana"))

    @property
    def payment_progress_click(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CLICK

    @property
    def payment_progress_payme(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_PAYME

    @property
    def payment_progress_cash(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CASH

    @property
    def payment_progress_title(self):
        return self.PAYMENT_PROGRESS_TITLE.get(self.payment_progress, "-")

    class Meta:
        managed = False

        verbose_name = _("Rasta holati")
        verbose_name_plural = _("Rasta holatlari")

# class StallGroup(models.Model):
#     number = models.CharField(max_length=20, verbose_name=_("Guruh nomi"), validators=[
#         RegexValidator(regex=r"^[a-z0-9]+$", )
#     ])
#     stalls = models.ManyToManyField(Stall, verbose_name=_("Rastalar"))

apps/stall/forms.py
from django import forms

from apps.stall.models import Stall


class StallCashForm(forms.Form):
    stall = forms.ModelChoiceField(queryset=Stall.objects.all())

apps/report/views.py
import datetime
from io import BytesIO

import xlsxwriter
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Sum, F, Case, When, Q, Count
from django.db.models.functions import Coalesce
from django.http import HttpResponse
from django.utils import timezone
from django.utils.text import slugify
from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from xlsxwriter.utility import xl_col_to_name

from apps.dashboard.filters import MonthFilter
from apps.main.models import Bazaar
from apps.parking.models import ParkingStatus
from apps.rent.models import ThingStatus, Thing, ThingData
from apps.report.filter import ClickFilter
from apps.shop.models import ShopPayment, ShopStatus, Shop
from apps.stall.models import StallStatus, Stall
from smartbozor.helpers import DayWeekCalendar, run_clickhouse_sql, range_d
from smartbozor.mixins import NormalizeDataMixin


class ReportTotalRevenueView(NormalizeDataMixin, LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    TITLE = _("Jami daromad")

    template_name = 'report/total-revenue.j2'
    permission_required = 'report.can_view_total_revenue'

    def render_to_response(self, context, **response_kwargs):
        if self.request.GET.get("export", '0') == '1':
            return self.export(context)

        return super().render_to_response(context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        bazaars = list(self.request.user.allowed_bazaar.order_by('id').all())

        context["bazaars"] = bazaars

        self.update_report(self.request, bazaars, context)

        return context

    def export(self, context):
        xls = BytesIO()

        workbook = xlsxwriter.Workbook(xls, {'in_memory': True})
        worksheet = workbook.add_worksheet(name="Jami daromad")

        header_format = workbook.add_format({
            'bg_color': '#263D54',
            'bold': True,
            'align': 'center',
            'valign': 'vcenter',
            'font_color': 'white',
            'border': 1
        })

        uzs_format = workbook.add_format({
            'num_format': '#,##0 "so\'m"',
            'align': 'right'
        })

        text_right_format = workbook.add_format({
            "align": "right",
        })

        text_center_format = workbook.add_format({
            "align": "center",
        })


        worksheet.write(0, 0, str(_("HUJJAT YARATILGAN SANA:")), text_right_format)
        worksheet.merge_range(0, 1, 0, 5, f"{timezone.localtime().now():%d.%m.%Y %H:%M}")

        worksheet.write(1, 0, str(_("SANA:")), text_right_format)
        worksheet.merge_range(1, 1, 1, 5, str(context["range_title"]))

        table_row = 3
        worksheet.merge_range(table_row, 0, table_row + 1, 0, str(_("Bozor nomi")), header_format)
        worksheet.merge_range(table_row, 1, table_row + 1, 1, str(_("Ish kuni")), header_format)

        things = context["things"]
        things_header = [
            [row.name, [_("Mavjud"), _("Band"), _("Narxi"), _("To'langan"), _("Jami tushum")]] for row in things
        ]
        thing_header_count = len(things_header[0][1])

        header = [
            [_("Rasta"), [_("Mavjud"), _("Band"), _("To'langan"), _("Jami tushum")]],
            [_("Magazin"), [_("Mavjud"), _("To'langan"), _("Jami tushum")]],
            *things_header,
            [_("Avtoturargoh"), [ _("Avtomobil soni"), _("To'langan"), _("Jami tushum")]],
            [_("JAMI"), [_("TO'LANGAN"), _("TUSHUM")]]
        ]

        header_col = 2
        for title, sub_title in header:
            worksheet.merge_range(table_row, header_col, table_row, header_col + len(sub_title) - 1, str(title), header_format)

            for n, st in enumerate(sub_title):
                col = header_col + n
                worksheet.write(table_row + 1, col,  str(st), header_format)

            header_col += len(sub_title)

        last_col = sum([len(st) for __, st in header]) + 1
        worksheet.set_column(0, 0, width=25)
        worksheet.set_column(1, last_col, width=12)

        working_days = context["working_days"]
        stall_count, stall_occupied_total, stall_paid_total = context["stall_count"], context["stall_occupied_total"], context["stall_paid_total"]
        shop_count, shop_paid_total, shop_occupied_total = context["shop_count"], context["shop_paid_total"], context["shop_occupied_total"]
        rent_count, rent_occupied_total, rent_paid_total = context["rent_count"], context["rent_occupied_total"], context["rent_paid_total"]
        parking = context["parking"]

        bazaar_thing_pt = dict()
        for key, value in rent_paid_total.items():
            bazaar_id, thing_id, pm = map(int, key.split("-"))
            if bazaar_id not in bazaar_thing_pt:
                bazaar_thing_pt[bazaar_id] = dict()

            bazaar_thing_pt[bazaar_id][thing_id] = bazaar_thing_pt[bazaar_id].get(thing_id, 0) + value

        paid_cols, total_cols = [], []
        for row, bazaar in enumerate(context['bazaars'], start=table_row + 2):
            worksheet.write(row, 0, bazaar.name)
            worksheet.write(row, 1, _("{0} kun").format(working_days.get(bazaar.id, 0)), text_center_format)
            # Stall
            stall_c = stall_count.get(bazaar.id, {})
            stall_ot = stall_occupied_total.get(bazaar.id, {})
            stall_pt, shop_pt = 0, 0

            for pm in Bazaar.PAYMENT_METHOD_DICT.keys():
                stall_pt += stall_paid_total.get(f"{bazaar.id}-{pm}", 0)
                shop_pt += shop_paid_total.get(f"{bazaar.id}-{pm}", 0)

            worksheet.write(row, 2, stall_c.get("count", 0), text_center_format)
            worksheet.write(row, 3, f"{stall_ot.get('count', 0)} / {stall_c.get('total', 0)}", text_center_format)
            worksheet.write(row, 4, stall_pt, uzs_format)
            worksheet.write(row, 5, stall_ot.get("total", 0), uzs_format)

            # Shop
            worksheet.write(row, 6, shop_count.get(bazaar.id, 0), text_center_format)
            worksheet.write(row, 7, shop_pt, uzs_format)
            worksheet.write(row, 8, shop_occupied_total.get(bazaar.id, 0), uzs_format)

            paid_cols, total_cols = [4, 7], [5, 8]
            thing_pt = bazaar_thing_pt.get(bazaar.id, {})
            for n, thing in enumerate(things):
                col, key = 9 + thing_header_count * n, f"{bazaar.id}-{thing.id}"
                thing_d = rent_count.get(key, {})
                thing_ot = rent_occupied_total.get(key, {})
                worksheet.write(row, col + 0, thing_d.get("count", 0), text_center_format)
                worksheet.write(row, col + 1, f"{thing_ot.get('count', 0)} / {thing_d.get('total', 0)}", text_center_format)
                worksheet.write(row, col + 2, thing_d.get("price", 0), uzs_format)
                worksheet.write(row, col + 3, thing_pt.get(thing.id, 0), uzs_format)
                worksheet.write(row, col + 4, thing_ot.get("total", 0), uzs_format)

                paid_cols.append(col + 3)
                total_cols.append(col + 4)

            col = 9 + thing_header_count * len(things)
            worksheet.write(row, col + 0, parking.get(bazaar.id, {}).get("paid_count", 0), text_center_format)
            worksheet.write(row, col + 1, parking.get(bazaar.id, {}).get("total_paid", 0), uzs_format)
            worksheet.write(row, col + 2, parking.get(bazaar.id, {}).get("total", 0), uzs_format)

            paid_cols.append(col + 1)
            total_cols.append(col + 2)

            paid_sum_args = ",".join([f"{xl_col_to_name(c)}{row + 1}" for c in paid_cols])
            worksheet.write_formula(row, col + 3, f"=SUM({paid_sum_args})", uzs_format)

            total_sum_args = ",".join([f"{xl_col_to_name(c)}{row + 1}" for c in total_cols])
            worksheet.write_formula(row, col + 4, f"=SUM({total_sum_args})", uzs_format)

        row = table_row + len(context["bazaars"]) + 3
        col = 9 + thing_header_count * len(things) + 3
        worksheet.write(row, 0, str(_("JAMI")))

        for col in paid_cols + total_cols + [col, col + 1]:
            col_name = xl_col_to_name(col)
            worksheet.write_formula(row, col, f"=SUM({col_name}{table_row + 3}:{col_name}{row})", uzs_format)

        workbook.close()

        xls.seek(0)

        name = "jami-daromad"
        response = HttpResponse(xls, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'inline; filename="{}-{:%Y-%m-%d-%H-%M}.xlsx"'.format(
            slugify(name),
            datetime.datetime.now()
        )

        return response

    @classmethod
    def update_report(cls, request, bazaars, context):
        if not bazaars:
            return

        data, months, selected_month = cls.normalize_data(request.GET.dict())
        bazaars_id, working_days = [], dict()
        for bazaar in bazaars:
            bazaars_id.append(bazaar.id)

            for day in range_d(selected_month, data["d"]):
                working_days[bazaar.id] = working_days.get(bazaar.id, 0) + (1 if bazaar.check_working_day(day) else 0)

        context["working_days"] = working_days

        context["stall_count"] = {
            row["bazaar_id"]: {
                "count": row["count"],
                "total": working_days.get(row["bazaar_id"], 0) * row["count"]
            } for row in Stall.objects.annotate(
                bazaar_id=F("section__area__bazaar_id")
            ).filter(bazaar_id__in=bazaars_id).values("bazaar_id").annotate(
                count=Count("id")
            ).values("bazaar_id", "count")
        }

        context["stall_occupied_total"] = {
            row["bazaar_id"]: row for row in
            MonthFilter(data, queryset=StallStatus.objects.filter(
                stall__section__area__bazaar_id__in=bazaars_id

templates/stall/_cash_modal.j2
<div class="modal fade" id="id-cash-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <h5 class="modal-header">
                {{ _("Naqd to'lov") }}
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </h5>
            <div class="modal-body">
                <form method="post" action="" id="id-cash-form" autocomplete="off">
                    {% csrf_token %}
                    <div class="mb-3 text-center">
                        <div class="title fs-5"></div>
                        <input type="hidden" name="stall" class="stall" value="0">
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary d-flex align-items-center">
                            <span class="spinner-border spinner-border-sm me-2 d-none"></span>
                            <span class="btn_title"></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/stall/_import_step1.j2
{% macro accordion(id, title, content) %}
    <div class="accordion accordion-flush">
        <div class="accordion-item border-bottom">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed text-uppercase" type="button" data-bs-toggle="collapse"
                        data-bs-target="#{{ id }}">
                    {{ title }}
                </button>
            </h2>
            <div id="{{ id }}" class="accordion-collapse collapse">
                <div class="accordion-body">
                    <table class="table table-striped table-bordered table-hover m-0">
                        <tbody>
                        {{ content }}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endmacro %}

{% macro simple_list(list) %}
    {% for n, p in list %}
        <tr>
            <td>{{ n }}</td>
            <td>{% if p is number %}{{ p|som }}{% else %}{{ p }}{% endif %}</td>
        </tr>
    {% endfor %}
{% endmacro %}

{% macro update_list(list) %}
    {% for stall, p in list %}
        <tr>
            <td>{{ stall.number }}</td>
            <td>{% if p != stall.price %}{{ stall.price|som }} &raquo; {% endif %}{{ p|som }}</td>
        </tr>
    {% endfor %}
{% endmacro %}

{% macro delete_list(list) %}
    {% for stall in list %}
        <tr>
            <td>{{ stall.number }}</td>
            <td>{{ stall.price|som }}</td>
        </tr>
    {% endfor %}
{% endmacro %}

{% if stall_wrong %}
    {{ accordion("id-import-wrong", _("Noto'g'ri kiritilgam rastalar - {0} ta").format(stall_wrong|length), simple_list(stall_wrong)) }}
{% endif %}

{% if duplicates %}
    {{ accordion("id-import-duplicates", _("Dublika rasta raqamlari - {0} ta").format(duplicates|length), simple_list(duplicates)) }}
{% endif %}

{% if stall_insert %}
    {{ accordion("id-import-insert", _("Yangi qo'shiladigan rastalar - {0} ta").format(stall_insert|length), simple_list(stall_insert)) }}
{% endif %}

{% if stall_update %}
    {{ accordion("id-import-update", _("Tahrirlanadigan rastalar - {0} ta").format(stall_update|length), update_list(stall_update)) }}
{% endif %}

{% if stall_delete %}
    {{ accordion("id-import-delete", _("Excelda topilmagan rastalar - {0} ta").format(stall_delete|length), delete_list(stall_delete)) }}
{% endif %}

{% if stall_skip %}
    {{ accordion("id-import-skip", _("O'zgarishsiz qolgan rastalar - {0} ta").format(stall_skip|length), delete_list(stall_skip)) }}
{% endif %}

templates/stall/_report.j2
<div class="d-flex mb-4 gap-4 flex-wrap">
    <div class="flex-grow-1">
        <div class="bg-white shadow rounded p-4">
            <h6>{{ total_title|default(_("Jami rastalar")) }}</h6>
            {% if total.total_count %}
                <div>{{ _("{0} ta / jami {1} ta").format(total.count, total.total_count) }}</div>
            {% else %}
                <div>{{ _("{0} ta").format(total.count) }}</div>
            {% endif %}
        </div>
    </div>
    <div class="flex-grow-1">
        <div class="bg-white shadow rounded p-4">
            <h6>{{ _("Band") }}</h6>
            <div>
                <span> {{ _("{0} ta").format(total.occupied_count) }}</span>
                <span class="text-danger">({{ _("qoldi {0} ta").format(total.count - total.occupied_count) }})</span>
            </div>
        </div>
    </div>
    <div class="flex-grow-1">
        <div class="bg-white shadow rounded p-4">
            <h6>{{ _("To'langan") }}</h6>
            <div>
                <span>{{ _("{0} ta").format(total.paid.count) }}</span>
                <span class="text-danger">({{ _("qoldi {0} ta").format(total.count - total.paid.count) }})</span>
            </div>
        </div>
    </div>
    <div class="flex-grow-1">
        <div class="bg-white shadow rounded p-4">
            <h6>{{ _("Jami summa") }}</h6>
            <div>{{ total.paid.total|som }}</div>
        </div>
    </div>
    {% for amount in total.amount %}
        <div class="flex-grow-1">
            <div class="bg-white shadow rounded p-4">
                <h6>{{ amount.payment_method_today|default(amount.payment_method)|payment_method_display }}</h6>
                <div>{{ amount.total|som }}</div>
            </div>
        </div>
    {% endfor %}
</div>

templates/stall/list.j2
{% extends 'layouts/auth.j2' %}

{% block before_page_content %}
    {% if total %}
        {% include 'stall/_report.j2' %}
    {% endif %}
{% endblock %}

{% block page_content %}
    <div class="mb-3">
        <form method="get" action="" class="d-flex">
            <div class="input-group">
                {{ filter.form.number }}
                {{ filter.form.is_paid }}

                <button type="submit" class="btn btn-primary text-nowrap">
                    <i class="bi bi-search me-2"></i>
                    {{ _("Qidirish") }}
                </button>
                {% if filter.form.is_bound %}
                    <a href="?" class="btn btn-danger">
                        <i class="bi bi-x"></i>
                    </a>
                {% endif %}
                <a href="?{{ request.GET.urlencode() }}&export=1" class="btn btn-info">
                    <i class="bi bi-download"></i>
                </a>
                {% if perms.stall.change_stall %}
                    <a href="{{ url("stall:import", bazaar.id) }}" class="btn btn-info">
                        <i class="bi bi-upload"></i>
                    </a>
                {% endif %}
            </div>
        </form>
    </div>

    <table class="table table-hover table-striped">
        <thead>
        <tr class="table-dark">
            <td>{{ _("Rasta raqami") }}</td>
            <td>{{ _("Narxi") }}</td>
            <td>{{ _("Badlik holati") }}</td>
            <td>{{ _("To'lov holati") }}</td>
            <td>{{ _("To'lov turi") }}</td>
            <td style="width: 1%"></td>
        </tr>
        </thead>
        <tbody>
        {% for row in object_list %}
            <tr {% if request.GET.hl|default(0)|int == row.id %}class="table-success"{% endif %}>
                <td>{{ row.number }}</td>
                <td>{{ row.price|som }}</td>
                <td>
                    {%- if not row.is_occupied_today -%}
                        <span class="badge bg-danger badge-occupied">{{ _("band emas") }}</span>
                    {%- else -%}
                        <span class="badge bg-success badge-occupied">{{ _("band") }}</span>
                    {%- endif -%}

                    {% if perms.stall.change_stallstatus and not row.is_paid_today %}
                        <button type="button" data-occupied="{{ row.id }}" class="btn btn-warning py-1 btn-sm">
                            <i class="bi bi-arrow-clockwise"></i>
                        </button>
                    {% endif %}
                </td>
                <td>
                    {% if not row.is_paid_today %}
                        {% if row.payment_progress_today > 0 %}
                            <span class="badge bg-info">{{ _("jarayonda") }}</span>
                        {% else %}
                            <span class="badge bg-danger">{{ _("to'lanmagan") }}</span>
                        {% endif %}
                    {% else %}
                        <span class="badge bg-success">{{ _("to'langan") }}</span>
                    {% endif %}
                </td>
                <td>
                    {{ row.payment_method_today|payment_method_display }}
                </td>
                <td class="text-nowrap text-end">
                    {% if not row.is_paid_today and perms.stall.add_stallstatus and bazaar.is_allow_cash and row.payment_progress_today == 0 %}
                        <button type="button" data-bs-toggle="modal" data-bs-target="#id-cash-modal"
                                data-title="{{ _("Rasta № {0}").format(row.number) }}"
                                data-btn_title="{{ _("{0} so'm to'landi").format(row.price|intcomma) }}"
                                data-stall="{{ row.id }}"
                                data-pk="{{ row.id }}"
                                class="btn btn-success btn-sm py-1">
                            <i class="bi bi-cash"></i> {{ _("Naqd") }}
                        </button>
                    {% endif %}
                    <a href="{{ url("stall:qr-code", row.id) }}" target="_blank" class="btn btn-info py-1 btn-sm"><i
                            class="bi bi-qr-code"></i></a>

                    {% if perms.stall.view_stallstatus %}
                        <button type="button" data-url="?id={{ row.id }}" data-bs-toggle="modal"
                                data-bs-target="#id-ajax-modal" class="btn btn-dark py-1 btn-sm">
                            <i class="bi bi-list"></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{{ _("Birorta ham rasta topilmadi") }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ bootstrap_pagination(page_obj, extra=request.GET.urlencode()) }}

    {% include "stall/_cash_modal.j2" %}
    {% include "include/ajax-modal.j2" %}
{% endblock %}

{% block extra_js %}
    <script src="{{ static("js/cash-modal.min.js") }}?{{ STATIC_VERSION }}"></script>
    {% if perms.stall.change_stallstatus %}
        <script src="{{ static("js/stall-occupied.min.js") }}?{{ STATIC_VERSION }}"></script>
    {% endif %}
{% endblock %}