apps/rent/urls.py
from django.urls import path

from apps.rent.views import RentListView, RentQrCode, RentBazaarChoice

app_name = "rent"
urlpatterns = [
    path("list/<int:pk>/", RentBazaarChoice.as_view(), name="list-bazaar"),
    path("list/<int:bazaar_id>-<int:pk>/", RentListView.as_view(), name="list"),
    path("qr-code/<int:bazaar_id>-<int:thing_id>-<int:number>/", RentQrCode.as_view(), name="qr-code"),
]

apps/shop/urls.py
from django.urls import path
from apps.shop.views import ShopListView, ShopQrCode, ShopImportView, ShopBazaarChoiceView

app_name = "shop"
urlpatterns = [
    path("list/", ShopBazaarChoiceView.as_view(), name="list-bazaar"),
    path("list/<int:pk>/", ShopListView.as_view(), name="list"),
    path("qr-code/<int:pk>/", ShopQrCode.as_view(), name="qr-code"),
    path("import/<int:pk>/", ShopImportView.as_view(), name="import"),
]

apps/stall/urls.py
from django.urls import path

from apps.stall.views import StallListView, StallQrCode, StallBazaarChoiceView, StallImportView

app_name = "stall"
urlpatterns = [
    path("list/", StallBazaarChoiceView.as_view(), name="list-bazaar"),
    path("list/<int:pk>/", StallListView.as_view(), name="list"),
    path("import/<int:pk>/", StallImportView.as_view(), name="import"),
    path("qr-code/<int:pk>/", StallQrCode.as_view(), name="qr-code")
]

smartbozor/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from django_otp.admin import OTPAdminSite

from apps.parking.views import ParkingActionView
from apps.payment.views import PaymentQrStallView, PaymentClick, PaymentPayme, PaymentQrShopView, PaymentQrRentView, \
    PaymentQrParkingView, PaymentQrPoint, PaymentClickPointProduct
from smartbozor.storages import stall_storage

urlpatterns = [
    path('control/', admin.site.urls),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("api/", include("apps.api.urls")),

    path("s/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrStallView.as_view(), name="stall-qr"),
    path("m/<int:bazaar_id>-<int:area_id>-<int:section_id>-<str:number>/", PaymentQrShopView.as_view(), name="shop-qr"),
    path("r/<int:bazaar_id>-<int:thing_id>-<int:number>/", PaymentQrRentView.as_view(), name="thing-qr"),
    path("p/<int:pk>/", PaymentQrParkingView.as_view(), name="parking-qr"),
    path("x/<int:pk>/", PaymentQrPoint.as_view(), name="point-qr"),

    path("parking/<str:action>/<str:token>/", ParkingActionView.as_view(), name="action"),

    path("payment/click/<str:name>/", PaymentClick.as_view(), name="payment-click"),
    path("payment/click/x/<str:slug>/", PaymentClickPointProduct.as_view(), name="payment-x-click"),
    path("payment/payme/<str:name>/", PaymentPayme.as_view(), name="payment-payme"),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(stall_storage.base_url, document_root=stall_storage.location)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path("", include( "apps.main.urls")),

    path("ai/", include("apps.ai.urls")),
    path("payment/", include("apps.payment.urls")),
    path("dashboard/", include( "apps.dashboard.urls")),
    path("account/", include( "apps.account.urls")),
    path("stall/", include( "apps.stall.urls")),
    path("shop/", include( "apps.shop.urls")),
    path("report/", include( "apps.report.urls")),
    path("parking/", include( "apps.parking.urls")),
    path("rent/", include( "apps.rent.urls")),
    path("camera/", include( "apps.camera.urls")),
)


admin.site.index_title = _('Smart bozor')
admin.site.site_header = _('Smart bozor')
admin.site.site_title = _('Smart bozor management')

if not settings.DEBUG:
    admin.site.__class__ = OTPAdminSite

apps/parking/models.py
import hashlib
import os
import secrets
import string

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import ForeignKey, Count, Value, Sum
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.main.models import Bazaar
from smartbozor.helpers import UploadTo, int_to_base36
from smartbozor.qrcode import generate_qr_code

ALPHABET = string.ascii_lowercase + string.digits


def generate_token(length: int = 32) -> str:
    return ''.join(secrets.choice(ALPHABET) for _ in range(length))


class Parking(models.Model):
    BILLING_MODE_ENTER = 0
    BILLING_MODE_EXIT = 1

    bazaar = models.ForeignKey(Bazaar, on_delete=models.RESTRICT, verbose_name=_("Bozor"))
    name = models.CharField(max_length=50, verbose_name=_("Turargoh nomi/raqami"))
    billing_mode = models.SmallIntegerField(choices=(
        (BILLING_MODE_ENTER, _("Pulni kirishi bilan hisoblash")),
        (BILLING_MODE_EXIT, _("Pulni chiqishda hisoblash")),
    ), default=BILLING_MODE_EXIT)
    save_image = models.BooleanField(default=False, verbose_name=_("Rasmlarni saqlash"))

    @property
    def qr_image_file(self):
        cache_path = settings.MEDIA_ROOT / "qr-codes" / "parking" / str(self.id // 1000)
        os.makedirs(cache_path, exist_ok=True)

        cache_file = cache_path / f"{self.qr_data}.png"
        if os.path.exists(cache_file):
            return cache_file

        img = generate_qr_code("rasta-click.png", f"{settings.QR_CODE_LINK_HOST}/p/{self.qr_data}/", "AVTOTURARGOH", str(self.id))
        img.save(cache_file, format="PNG", optimize=True, compress_level=9, dpi=(300, 300))
        img.close()

        return cache_file

    @property
    def qr_data(self):
        return str(self.id)

    @classmethod
    def extract_query(cls, data):
        data_str = str(data)
        if data_str.startswith("1"):
            return int(data_str[1:])
        elif data_str.startswith("9"):
            return int_to_base36(int(data_str[1:]))

        raise ValueError

    def get_payment_amount(self, query, in_transaction=False):
        after = timezone.now().date().replace(day=1) - relativedelta(months=6)
        qs = ParkingStatus.objects.filter(
            parking=self,
            is_paid=False,
            price__gt=0,
            payment_progress=0,
            date__gte=after,
        ).order_by('id')

        if in_transaction:
            qs = qs.select_for_update()

        if isinstance(query, str):
            rows = qs.filter(number=query.upper()).all()
        else:
            rows = qs.all()[:query]

        payment_amount, selected_id, selected_rows = 0, [], []
        for row in rows:
            payment_amount += row.price
            selected_id.append(row.id)
            selected_rows.append(row)

        selected_id.sort()

        data = ",".join(map(str, selected_id)).encode("utf-8")
        digest = hashlib.sha256(data).digest()
        order_id = (self.id << 32) | int.from_bytes(digest[:4], byteorder="big", signed=False)

        return selected_rows, payment_amount, order_id

    def __str__(self):
        if hasattr(self, "display_name"):
            return self.display_name

        return f"Parking {self.name}"

    class Meta:
        verbose_name = _("Avtoturargoh")
        verbose_name_plural = _("Avtoturargohlar")


class ParkingPrice(models.Model):
    parking = models.ForeignKey(Parking, on_delete=models.RESTRICT, verbose_name=_("Avtoturargoh"))
    duration = models.IntegerField(
        default=0,
        verbose_name=_("Davomiyligi (sekundda)"),
        help_text=_(
            "Ko'rsatilgan qiymatdan o'tsa narx hisoblanadi. Masalan 3600 qo'yilsa, 1 soatdan oshsa ma'noni anglatadi."),
        validators=[MinValueValidator(0)],
    )
    price = models.IntegerField(
        verbose_name=_("Narxi"),
        help_text=_("Agar 0 qo'yilsa, tekin ekanligini anglatadi"),
        validators=[MinValueValidator(0)]
    )
    cash_receipts = models.IntegerField(default=0, verbose_name=_("Naqd cheklar soni"), editable=False)

    class Meta:
        verbose_name = _("Avtoturargoh narxi")
        verbose_name_plural = _("Avtoturargoh narxlari")


class ParkingCamera(models.Model):
    ROLE_ENTER = 0
    ROLE_EXIT = 1

    parking = ForeignKey(Parking, on_delete=models.RESTRICT, verbose_name=_("Avtoturargoh"))
    role = models.SmallIntegerField(choices=(
        (ROLE_ENTER, _("Kirish")),
        (ROLE_EXIT, _("Chiqish")),
    ), default=ROLE_ENTER, verbose_name=_("Roli"))
    mac = models.CharField(max_length=12, verbose_name=_("MAC"), null=True, blank=True, default=None)
    token = models.CharField(max_length=32, verbose_name=_("Token"), default=generate_token, editable=False,
                             unique=True)

    class Meta:
        verbose_name = _("Kamera")
        verbose_name_plural = _("Kameralar")


class ParkingStatus(models.Model):
    LICENSE_PLATE_UNKNOWN = "UNKNOWN"

    PAYMENT_PROGRESS_CLICK = 1
    PAYMENT_PROGRESS_PAYME = 2
    PAYMENT_PROGRESS_CASH = 3

    PAYMENT_PROGRESS_TITLE = {
        PAYMENT_PROGRESS_CLICK: "Click",
        PAYMENT_PROGRESS_PAYME: "Payme",
        PAYMENT_PROGRESS_CASH: _("Naqd"),
    }

    parking = models.ForeignKey(Parking, on_delete=models.RESTRICT, verbose_name=_("Avtoturargoh"))
    date = models.DateField(verbose_name=_("Sana"))
    number = models.CharField(max_length=20, verbose_name=_("Avtoraqam"))
    is_paid = models.BooleanField(default=False, verbose_name=_("To'langan"))
    payment_method = models.IntegerField(default=0, verbose_name=_("To'lov turi"))
    payment_progress = models.SmallIntegerField(default=0, verbose_name=_("To'lov jarayoni"))
    price = models.IntegerField(default=0, verbose_name=_("Narxi"))
    duration = models.IntegerField(default=0, verbose_name=_("Davomiyligi"))
    enter_count = models.IntegerField(default=0, verbose_name=_("Kirish soni"))
    leave_count = models.IntegerField(default=0, verbose_name=_("Chiqish soni"))
    enter_at = models.DateTimeField(verbose_name=_("Kirgan vaqti"))
    leave_at = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_("Chiqqan vaqti"))
    paid_at = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_("To'langan vaqti"))
    enter_image = models.ImageField(upload_to=UploadTo("parking/%Y-%m/enter"), null=True, blank=True, default=None,
                                    verbose_name=_("Kirish rasmi"))
    leave_image = models.ImageField(upload_to=UploadTo("parking/%Y-%m/exit"), null=True, blank=True, default=None,
                                    verbose_name=_("Chiqish rasmi"))

    @property
    def payment_progress_click(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CLICK

    @property
    def payment_progress_payme(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_PAYME

    @property
    def payment_progress_cash(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CASH

    @property
    def payment_progress_title(self):
        return self.PAYMENT_PROGRESS_TITLE.get(self.payment_progress, "-")

    class Meta:
        managed = False

        verbose_name = _("Avtoturargoh holati")
        verbose_name_plural = _("Avtoturargoh holatlari")


class ParkingWhitelist(models.Model):
    region = models.ForeignKey("main.Region", on_delete=models.RESTRICT, verbose_name=_("Viloyat"), null=True,
                               blank=True)
    district = models.ForeignKey("main.District", on_delete=models.RESTRICT, verbose_name=_("Tuman"), null=True,
                                 blank=True)
    bazaar = models.ForeignKey("main.Bazaar", on_delete=models.RESTRICT, verbose_name=_("Bozor"), null=True, blank=True)
    pattern = models.CharField(max_length=100, verbose_name=_("Regex"))

    class Meta:
        verbose_name = _("Oq ro'yxat")
        verbose_name_plural = _("Oq ro'yxat")

apps/rent/models.py
import os

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.main.models import Bazaar
from smartbozor.qrcode import generate_qr_code
from smartbozor.translation import i18n


@i18n
class Thing(models.Model):
    name_uz = models.CharField(max_length=100)

    @classmethod
    def get_qr_data(cls, bazaar, thing, number):
        return "{0}-{1}-{2}".format(
            bazaar.id,
            thing.id,
            number
        )

    @classmethod
    def get_qr_img_file(cls, bazaar, thing, number):
        cache_path = settings.MEDIA_ROOT / "qr-codes" / "rent" / str(bazaar.id // 1000)
        os.makedirs(cache_path, exist_ok=True)

        qr_data = cls.get_qr_data(bazaar, thing, number)
        cache_file = cache_path / f"{qr_data}.png"
        if os.path.exists(cache_file):
            return cache_file

        img = generate_qr_code("rasta-click.png", f"{settings.QR_CODE_LINK_HOST}/r/{qr_data}/", thing.name.upper(), str(number))
        img.save(cache_file, format="PNG", optimize=True, compress_level=9, dpi=(300, 300))
        img.close()

        return cache_file

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Buyum")
        verbose_name_plural = _("Buyumlar")


class ThingData(models.Model):
    thing = models.ForeignKey(Thing, on_delete=models.RESTRICT, verbose_name=_("Buyum"))
    bazaar = models.ForeignKey(Bazaar, on_delete=models.RESTRICT, verbose_name=_("Bozor"))
    count = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999)], verbose_name=_("Netcha mavjud"))
    price = models.BigIntegerField(validators=[MinValueValidator(0)], verbose_name=_("Ijara narxi"))

    def get_qr_image_file(self, number):
        return Thing.get_qr_img_file(self.bazaar, self.thing, number)

    def __str__(self):
        return f"{self.bazaar} - {self.thing}"

    class Meta:
        unique_together = ('thing', 'bazaar')
        verbose_name = _("Bozordagi buyum")
        verbose_name_plural = _("Bozordagi buyumlar")


class ThingStatus(models.Model):
    PAYMENT_PROGRESS_CLICK = 1
    PAYMENT_PROGRESS_PAYME = 2
    PAYMENT_PROGRESS_CASH = 3

    PAYMENT_PROGRESS_TITLE = {
        PAYMENT_PROGRESS_CLICK: "Click",
        PAYMENT_PROGRESS_PAYME: "Payme",
        PAYMENT_PROGRESS_CASH: _("Naqd"),
    }

    bazaar = models.ForeignKey(Bazaar, on_delete=models.RESTRICT, verbose_name=_("Bozor"))
    thing = models.ForeignKey(Thing, on_delete=models.RESTRICT, verbose_name=_("Rasta"))
    number = models.IntegerField(verbose_name=_("Buyum raqami"))
    date = models.DateField(verbose_name=_("Kun"))
    is_occupied = models.BooleanField(default=False, verbose_name=_("Band bo'lgan"))
    is_paid = models.BooleanField(default=False, verbose_name=_("To'lov qilingan"))
    payment_method = models.IntegerField(default=0, verbose_name=_("To'lov turi"))
    payment_progress = models.SmallIntegerField(default=0, verbose_name=_("To'lov jarayoni"))
    price = models.IntegerField(verbose_name=_("Narxi"))
    occupied_at = models.DateTimeField(null=True, default=None, blank=True, verbose_name=_("Band qilingan sana"))
    paid_at = models.DateTimeField(null=True, default=None, blank=True, verbose_name=_("To'lov qilingan sana"))

    @property
    def payment_progress_click(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CLICK

    @property
    def payment_progress_payme(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_PAYME

    @property
    def payment_progress_cash(self):
        return self.payment_progress == self.PAYMENT_PROGRESS_CASH

    @property
    def payment_progress_title(self):
        return self.PAYMENT_PROGRESS_TITLE.get(self.payment_progress, "-")

    class Meta:
        managed = False

        verbose_name = _("Buyum holati")
        verbose_name_plural = _("Buyum holatlari")

apps/rent/forms.py
from django import forms


class ThingCashForm(forms.Form):
    number = forms.IntegerField()

apps/shop/forms.py
from django import forms

from apps.shop.models import Shop


class ShopCashForm(forms.Form):
    shop = forms.ModelChoiceField(queryset=Shop.objects.all())
    amount = forms.IntegerField(min_value=1)

apps/stall/forms.py
from django import forms

from apps.stall.models import Stall


class StallCashForm(forms.Form):
    stall = forms.ModelChoiceField(queryset=Stall.objects.all())

templates/payment/parking.j2
{% extends 'layouts/base.j2' %}

{% block extra_style %}
    <style>
        .payme-button input {
            height: 48px !important;
        }
    </style>
{% endblock %}

{% set cash_allowed = user.is_authenticated and bazaar.is_allow_cash and perms.parking.view_parking and perms.parking.add_parkingstatus and bazaar.id in ALLOWED_BAZAAR_ID %}

{% block content %}
    <div class="container pt-4 px-4">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="shadow bg-white rounded-3 p-4">
                    <div class="text-center mb-4">
                        <h4 class="text-uppercase">{{ bazaar }}</h4>
                        <hr/>
                        {{ bootstrap_messages() }}

                        <div class="text-uppercase">
                            {{ parking.name }}
                        </div>
                    </div>

                    <table class="table">
                        <tbody>
                        <tr>
                            <th class="bg-primary text-white w-50">{{ _("To'lov qilinmaganlar soni") }}</th>
                            <td>{{ _("{0} ta").format(not_paid.count|intcomma) }}</td>
                        </tr>
                        <tr>
                            <th class="bg-primary text-white w-50">{{ _("To'lov qilinmagan") }}</th>
                            <td>{{ not_paid.total_amount|som }}</td>
                        </tr>

                        {% if parking_prices|length > 0 %}
                            <tr>
                                <th colspan="2" class="bg-dark text-white text-center">{{ _("Narxlar") }}</th>
                            </tr>
                        {% endif %}
                        {% for pp in parking_prices %}
                            {% set next_pp = parking_prices[loop.index] if loop.index < parking_prices|length else None %}
                            <tr>
                                <th class="bg-primary text-white">
                                    {%- if parking_prices|length == 1 -%}
                                        {{ _("Kirish narxi") }}
                                    {%- elif next_pp -%}
                                        {{ _("{0} minutgacha").format(next_pp.duration // 60) }}
                                    {%- else -%}
                                        {{ _("{0} minutdan oshsa").format(pp.duration // 60) }}
                                    {%- endif -%}
                                </th>
                                <td>
                                    {%- if pp.price == 0 -%}{{ _("Tekin") }}
                                        {%- else -%}{{ pp.price|som }}
                                    {%- endif -%}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                    {% if payment_amount > 0 %}
                        {% if (order_nonce|string).startswith("9") %}
                            <div class="alert alert-info">{{ _("Avtomobil raqami: {}. To'lanmanga {} ta").format(query, found_rows) }}</div>
                        {% else %}
                            <div class="alert alert-info">{{ _("Tanlangan {} ta").format(found_rows) }}</div>
                        {% endif %}
                        <div class="d-flex justify-content-center mb-5 align-items-center">
                            <div class="bg-success py-1 px-3 rounded-3 fs-5 fw-bold">+{{ payment_amount|som }}</div>
                            <a href="?"
                               class="ms-3 text-decoration-none d-blok py-2">{{ _("Boshqa qiymat kiritish") }}</a>
                        </div>
                    {% endif %}

                    {% if payment_amount == 0 and not_paid.total_amount > 0 %}
                        {% set is_invalid = "query" in request.GET %}
                        <form method="get" action="" autocomplete="off">
                            <div class="mb-3">
                                <input name="query" type="text"
                                       class="form-control {% if is_invalid %}is-invalid{% endif %}"
                                       placeholder="{{ _("Avtomobillar sonini yoki raqamini kiriting") }}"/>
                                {% if is_invalid %}
                                    {% if request.GET.query.isdigit() %}
                                        <div class="invalid-feedback">{{ _("Iltimos, qiymatni to'g'ri kiriting") }}</div>
                                    {% else %}
                                        <div class="invalid-feedback">{{ _("Iltimos, avtomobil raqamini to'g'ri kiriting") }}</div>
                                    {% endif %}
                                {% else %}
                                    <div class="form-text">{{ _("Avtomobillar soni {0} gacha kiritilishi lozim.").format(not_paid.count|intcomma) }}</div>
                                {% endif %}
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">{{ _("To'lov turini tanlash") }}</button>
                            </div>
                        </form>
                    {% elif order_nonce > 0 %}
                        <div class="d-flex justify-content-center align-items-center flex-wrap gap-4">
                            {% if cash_allowed %}
                                <button class="btn btn-cash fs-5 confirm px-4 py-0 d-flex align-items-center justify-content-center rounded-1"
                                        data-bs-toggle="modal" data-bs-target="#id-cash-modal"
                                        data-title="{{ _("Avtoturargoh {0}").format('"' + parking.name + '"') }}"
                                        data-parking="{{ parking.id }}"
                                        data-pk="{{ parking.id }}"
                                        data-amount="{{ order_nonce|safe }}"
                                        data-order_id="{{ order_id|safe }}"
                                        data-payment_amount_readonly="{{ payment_amount|safe }}"
                                        data-url="{{ url("parking:list", bazaar.id) }}">
                                    <i class="bi bi-cash me-2"></i>
                                    {{ _("Naqd") }}
                                </button>
                            {% endif %}

                            {% if bazaar.is_allow_click %}
                                <a class="btn click-btn px-4 py-0 d-flex align-items-center justify-content-center rounded-1"
                                   href="https://my.click.uz/services/pay?service_id={{ bazaar.click_service_id }}&merchant_id={{ bazaar.click_merchant_id }}&amount={{ payment_amount }}&transaction_param=p-{{ order_id }}-{{ order_nonce }}&return_url={{ request.build_absolute_uri() }}">
                                    <img src="{{ static("img/click.svg") }}" style="height: 16px" alt="Click"/>
                                </a>
                            {% endif %}

                            {% if bazaar.is_allow_payme %}
                                <form id="form-payme" method="POST" action="https://checkout.paycom.uz/"
                                      style="height: 48px;">
                                    <input type="hidden" name="merchant" value="{{ bazaar.payme_merchant }}">
                                    <input type="hidden" name="account[order_id]"
                                           value="p-{{ order_id }}-{{ order_nonce }}">
                                    <input type="hidden" name="amount" value="{{ payment_amount * 100 }}">
                                    <input type="hidden" name="lang" value="uz">
                                    <input type="hidden" name="button" data-type="png" value="colored">
                                    <div class="payme-button"></div>
                                </form>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% include "parking/_cash_modal.j2" %}
{% endblock %}

{% block extra_js %}
    {% if bazaar.is_allow_payme %}
        <script src="https://cdn.paycom.uz/integration/js/checkout.min.js"></script>
        <script>document.addEventListener("DOMContentLoaded", () => {
            Paycom.Button('#form-payme', '.payme-button')
        })</script>
    {% endif %}

    {% if cash_allowed %}
        <script src="{{ static("js/cash-modal.min.js") }}?{{ STATIC_VERSION }}"></script>
    {% endif %}
{% endblock %}

templates/payment/point.j2
{% extends 'layouts/base.j2' %}

{% block content %}
    <div class="container pt-4 px-4">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="shadow bg-white rounded-3 p-4">
                    <div class="text-center mb-4">
                        <h4 class="text-uppercase">
                            {{ object.point.district.region }} &raquo;
                            {{ object.point.district }}
                            {% if object.point.name %}
                                &raquo; {{ object.point.name }}
                            {% endif %}
                        </h4>
                        <hr/>
                        {{ bootstrap_messages() }}

                        {% if object.name %}
                            <div class="text-uppercase">
                                {{ object.name }}
                            </div>
                        {% endif %}
                    </div>

                    {% if is_available %}
                        {% include 'payment/includes/point_form.j2' %}
                    {% else %}
                        <div class="alert alert-danger">{{ _("Tizim vaqtincha o'chirilgan") }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}